---
- name: Instalar fail2ban
  apt:
    name: fail2ban
    state: present

- name: Desplegar configuracion de jail para sshd
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"
  notify: reiniciar fail2ban

- name: Asegurar que fail2ban esta habilitado y activo
  systemd:
    name: fail2ban
    enabled: true
    state: started
